config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :playlists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "tracks#index"
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_tracks
  has_many :tracks, through: :playlist_tracks

  validates :name, presence: true
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)

    if @playlist.save
      redirect_back_or_to(playlists_path)
    else
      render :new
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= render_form_for @playlist do |form| %>
  <div class="my-2">
    <%= form.text_field :name, autofocus: true %>
  </div>
  <div class="flex justify-between items-center">
    <%= form.submit "Create", class: "text-sm px-2 py-1" %>
    <%= render_button "Cancel", as: :link, href: playlists_path, variant: :ghost, class: "text-sm px-2 py-1" %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div class="space-y-1 p-2"  ">
  <%= link_to playlist_path(playlist), class: "focus-visible:ring-ring hover:bg-accent
            hover:text-accent-foreground inline-flex h-9 w-full items-center justify-start
            rounded-md px-4 py-2 text-sm font-normal transition-colors focus-visible:outline-none
            focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50" , turbo_frame: "_top", data:
            {turbo_frame: "_top", controller: "playlists", action: "drop->playlists#addTrack dragover->playlists#trackOver dragleave->playlists#trackLeave dragend->playlists#trackLeave", playlist_id: playlist.id} do %>
    <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="mr-2 h-4 w-4">
      <path d="M21 15V6"></path>
      <path d="M18.5 18a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"></path>
      <path d="M12 12H3"></path>
      <path d="M16 6H3"></path>
      <path d="M12 18H3"></path>
    </svg>
    <%= playlist.name %>
  <% end %>
</div>

app/views/playlists/_playlists.html.erb
<%= turbo_frame_tag "playlists" do %>
  <div class="space-y-4">
    <div>
      <div class="flex justify-between items-center pl-6 pr-3">
        <h2 class="relative text-lg font-semibold tracking-tight">Playlists</h2>
        <%= render_button as: :link, href: new_playlist_path, variant: :ghost, class: "px-2" do %>
          + Add
        <% end %>
      </div>
      <%= yield %>
      <div dir="ltr" class="relative px-1">
        <div class="h-full w-full rounded-[inherit]">
          <div style="min-width: 100%; display: table">
            <div data-controller="playlists">
              <%= render collection: Playlist.all, partial: "playlists/playlist" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/playlists/index.html.erb
<%= render "playlists/playlists" %>

app/views/playlists/new.html.erb
<%= render "playlists/playlists" do %>
  <div class="px-3"><%= render "form" %></div>
<% end %>